preloader:
  enable: true
  source: 1
  pace_css_url:
# 主页subtitle
subtitle:
  enable: true
  # Typewriter Effect (打字效果)
  effect: true
  startDelay: 300 # time before typing starts in milliseconds
  typeSpeed: 200 # type speed in milliseconds
  backSpeed: 800 # backspacing speed in milliseconds
  # loop (循环打字)
  loop: true
  # source 调用三方服务
  # source: false 开关调用
  # subtitle 会先显示 source , 再显示 sub 的內容
  source: true
  # 如果关闭打字效果，subtitle 只会显示 sub 的第一行文字
  sub:
    - 把所有的春天，都揉进这一个青春。把所有看不见的言语变成秘密，关上了门 & #44; 而今渐觉出蓬蒿
    - 你会发现世界新的尽头，下雨会有彩色的洋流，珊瑚里有被浇灌的梦，街角有海獭等着你的糖球 & #44; 直待凌云始道高
    - 可是啊，我却，却愿意去相信，最渺小最温柔最柔软最无畏的你
    - 借一方三九天里烈烈暖阳，熔这茫茫人间刺骨凉
    - 也路过，旋转的星空；发现光颜色万种，风吹来云在翻涌，都抵不过你的笑容
    - 我也想，能陪你一起走啊，直到这世界崩塌。可是啊，走过长夜的你，不再需要被牵挂
    - 有些遗憾要学会放下，生活无需太重的行囊
    - 既然相遇始终来自于时光的馈赠，那么离别时也一定要微笑着回忆放心中
    - 可以哭了，可以笑着说结束了
    - 也敬你一杯，因为值得
    - 一定是你来时太小心，怕我再想起你
    - 无名的人啊，我敬你一杯酒，敬你的沉默，和每一声怒吼
    - 我不再迷茫，思念是唯一的行囊。满天的星光，有一颗是你的方向。
    - May all the beauty be blessed.